version: "3.2"
services:
  erabliere-api:
    image: "erabliereapi/erabliereapi:latest"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;"
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp-web-api.pfx
      KestrelBinder.ErrorOnUnknowConfiguration: false
      USE_CORS: "True"
      CORS_ORIGINS: "*"
      CORS_HEADERS: "*"
      CORS_METHODS: "*"
      USE_SQL: "true"
      SQL_CONNEXION_STRING: "Server=tcp:sql,1433;Initial Catalog=ErabliereAPI;Persist Security Info=False;User ID=SA;Password=${SAPASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
      SQL_USE_STARTUP_MIGRATION: "true"
      DEBUG_HEADERS: "true"
      LOG_SQL: "Console"
      USE_AUTHENTICATION: "true"
      USE_SWAGGER_AUTHORIZATIONCODE_WORKFLOW: "true"
      USE_SWAGGER_PKCE: "true"
      SWAGGER_AUTHORIZATION_URL: "https://localhost:5005/connect/authorize"
      SWAGGER_TOKEN_URL: "https://localhost:5005/connect/token"
      OIDC_CLIENT_ID: "swagger-dev"
      OIDC_CLIENT_PASSWORD: "D6VDPBGKjmoyKkP~yFnxvMlLqS"
      OAUTH2_REDIRECT_URL: "https://localhost:5001/api/oauth2-redirect.html"
      OIDC_AUDIENCE: "http://erabliere-api"
      OIDC_SCOPES: "erabliereapi"
      OIDC_AUTHORITY: "https://identite-api"
      EMAIL_CONFIG_PATH: "-"
    ports:
      - "5001:443"
    volumes:
      - ./config:/app/wwwroot/assets/config
      - type: bind # Using a bind volume as only this single file from `certs` directory should end up in the container.
        source: ./config/oauth-oidc.json
        target: /app/wwwroot/assets/config/oauth-oidc.json
      - ./ErabliereApi/certs:/https/
      - type: bind # Using a bind volume as only this single file from `certs` directory should end up in the container.
        source: ./certs/aspnetapp-root-cert.cer
        target: /https-root/aspnetapp-root-cert.cer
    depends_on:
      - sql
      - identite-api
    entrypoint: /app/docker-entrypoint.sh
  identite-api:
    image: "erabliereapi/serveuridentite:latest"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;"
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp-identity-server.pfx
      ISSUER_URI: "https://identite-api:443"
      SECRETS_FOLDER: /app/secrets
    ports:
      - "5005:443"
    volumes:
      - ./IdentityServer/ErabliereApi.IdentityServer/certs:/https/
      - type: bind # Using a bind volume as only this single file from `certs` directory should end up in the container.
        source: ./certs/aspnetapp-root-cert.cer
        target: /https-root/aspnetapp-root-cert.cer
      - ./IdentityServer/config:/app/secrets
      - type: bind # Using a bind volume as only this single file from `certs` directory should end up in the container.
        source: ./IdentityServer/config/ErabliereApi.IdentityServer.Users.json
        target: /app/ErabliereApi.IdentityServer.Users.json
        source: ./IdentityServer/config/ErabliereApi.IdentityServer.Config.json
        target: /app/ErabliereApi.IdentityServer.Config.json
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${SAPASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd","-U SA -P ${SAPASSWORD} -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'"]
        interval: 10s
        timeout: 10s
        retries: 6
