kind: ConfigMap
apiVersion: v1
metadata:
  name: erabliereiu-cypress-config
  labels:
    app: cypress-pod
data:
  cypress.json: |
    {
      "integrationFolder": "/testing/cypress/integration",
      "supportFile": "/testing/cypress/support",
      "videosFolder": "/test-results/cypress/videos",
      "screenshotsFolder": "/test-results/cypress/screenshots",
      "pluginsFile": "/testing/cypress/plugins/index.ts",
      "fixturesFolder": "/testing/cypress/fixtures",
      "baseUrl": "http://erabliere-api-service",
      "projectId": "7cxkq4"
    }
  tsconfig.json: |
    {
      "compilerOptions": {
        "target": "es5",
        "lib": ["es5", "dom"],
        "types": ["cypress"]
      },
      "include": ["**/*.ts"]
    }
