kind: Pod
apiVersion: v1
metadata:
  name: cypress-pod
  labels:
    app: cypress-pod
spec:
  containers:
  - name: file-copy
    image: ubuntu
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: shared-data
      mountPath: /test-results
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: "20m"
        memory: "100Mi"
  - name: cypress-pod
    image: cypress/included:9.5.4
    command: 
      - /bin/sh
      - -c
      - |
        cp /cypress-config/tsconfig.json /testing/cypress/tsconfig.json
        cp /cypress-config/cypress.json /testing/cypress/cypress.json
        cd /testing/cypress
        npm install -g typescript
        #cypress run
        #cypress run --config-file /cypress-config/cypress.json --config video=false
        tail -f /dev/null
    env:
    - name: DEBUG
      value: "cypress:*"
    volumeMounts:
    - name: cypress-fixtures
      mountPath: /testing/cypress/fixtures
      readOnly: true
    - name: cypress-integration
      mountPath: /testing/cypress/integration
      readOnly: true
    - name: cypress-support
      mountPath: /testing/cypress/support
      readOnly: true
    - name: cypress-plugins
      mountPath: /testing/cypress/plugins
      readOnly: true
    - name: cypress-config
      mountPath: /cypress-config
      readOnly: true
    - name: shared-data
      mountPath: /test-results
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: "200m"
        memory: "100Mi"
  volumes:
  - name: cypress-fixtures
    configMap:
      name: erabliereiu-cypress-fixtures
  - name: cypress-integration
    configMap:
      name: erabliereiu-cypress-integration
  - name: cypress-support
    configMap:
      name: erabliereiu-cypress-support
  - name: cypress-plugins
    configMap:
      name: erabliereiu-cypress-plugins
  - name: cypress-config
    configMap:
      name: erabliereiu-cypress-config
  - name: shared-data
    emptyDir: {}