kind: Pod
apiVersion: v1
metadata:
  name: cypress-pod
  labels:
    app: cypress-pod
spec:
  containers:
  - name: file-copy
    image: ubuntu
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: shared-data
      mountPath: /test-results
  - name: cypress-pod
    image: cypress/included:9.5.4
    command: ["cypress"]
    args: ["run", "--spec", "/testing/cypress"]
    volumeMounts:
    - name: cypress-fixtures
      mountPath: /testing/cypress/fixtures
      readOnly: true
    - name: cypress-integration
      mountPath: /testing/cypress/integration
      readOnly: true
    - name: cypress-support
      mountPath: /testing/cypress/support
      readOnly: true
    - name: cypress-plugins
      mountPath: /testing/cypress/plugins
      readOnly: true
    - name: cypress-config
      mountPath: /cypress-config
      readOnly: true
    - name: shared-data
      mountPath: /test-results
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: "100m"
        memory: "100Mi"
  volumes:
  - name: cypress-fixtures
    configMap:
      name: erabliereiu-cypress-fixtures
  - name: cypress-integration
    configMap:
      name: erabliereiu-cypress-integration
  - name: cypress-support
    configMap:
      name: erabliereiu-cypress-support
  - name: cypress-plugins
    configMap:
      name: erabliereiu-cypress-plugins
  - name: cyress-config
    configMap:
      name: erabliereiu_cypress-config
  - name: shared-data
    emptyDir: {}