kind: Pod
apiVersion: v1
metadata:
  name: securetesting-newman
  labels:
    app: securetesting-newman
spec:
  containers:
  - name: securetesting-newman
    image: erabliereapi/securetesting-newman:latest
    command: 
      - /bin/sh
      - -c
      - |
        #!/bin/sh
        newman run /testing/postman/ErabliereAPI.postman_collection.json --env-var url=http://erabliere-api-service
        sleep 60
        exit 0
    volumeMounts:
    - name: erabliereapi-test
      mountPath: /testing/postman
      readOnly: true
  volumes:
  - name: securetesting-secret
    secret:
      secretName: password-secret
  - name: erabliereapi-test
    configMap:
      name: erabliereapi-postman-test