apiVersion: apps/v1
kind: Deployment
metadata:
  name: erabliereapi-deployment
  labels:
    app: erabliereapi
  namespace: erabliere-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erabliereapi
  template:
    metadata:
      labels:
        app: erabliereapi
    spec:
      volumes:
      - name: email-config-secret
        secret:
          secretName: erabliereapi-email-config
      containers:
      - name: erabliereapi
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:#{IMAGE_TAG}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: email-config-secret
          mountPath: /app/secret
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: USE_CORS
          value: "True"
        - name: CORS_ORIGINS
          value: "*"
        - name: CORS_HEADERS
          value: "*"
        - name: CORS_METHODS
          value: "*"
        - name: USE_SQL
          value: "true"
        - name: SQL_CONNEXION_STRING
          value: "Data Source=erabliere-db-service;Initial Catalog=ErabliereAPI;User ID=SA;Password=#{DATABASE_PASSWORD}"
        - name: SQL_USE_STARTUP_MIGRATION
          value: "true"
        - name: DEBUG_HEADERS
          value: "false"
        - name: LOG_SQL
          value: "-"
        - name: USE_AUTHENTICATION
          value: "true"
        - name: USE_SWAGGER_AUTHORIZATIONCODE_WORKFLOW
          value: "true"
        - name: USE_SWAGGER_PKCE
          value: "true"
        - name: SWAGGER_AUTHORIZATION_URL
          value: "https://oauth2.freddycoder.com/connect/authorize"
        - name: SWAGGER_TOKEN_URL
          value: "https://oauth2.freddycoder.com/connect/token"
        - name: OIDC_CLIENT_ID
          value: "swagger-prod"
        - name: OIDC_CLIENT_PASSWORD
          value: "#{OIDC_CLIENT_PASSWORD}"
        - name: OAUTH2_REDIRECT_URL
          value: "https://erabliereapi.freddycoder.com/api/oauth2-redirect.html"
        - name: OIDC_AUDIENCE
          value: "http://erabliere-api"
        - name: OIDC_AUTHORITY
          value: "https://oauth2.freddycoder.com"
        - name: EMAIL_CONFIG_PATH
          value: "/app/secret/emailConfig.json"
        