apiVersion: apps/v1
kind: Deployment
metadata:
  name: erabliereapi-deployment
  labels:
    app: erabliereapi
  namespace: erabliere-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erabliereapi
  template:
    metadata:
      labels:
        app: erabliereapi
    spec:
      containers:
      - name: erabliereapi
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:#{GITHUB_RUN_ID}
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: USE_CORS
          value: "True"
        - name: CORS_ORIGINS
          value: "*"
        - name: CORS_HEADERS
          value: "*"
        - name: CORS_METHODS
          value: "*"
        - name: SWAGGER_SERVER_URL
          value: "https://erabliereapi.freddycoder.com"
        - name: USE_SQL
          value: "true"
        - name: SQL_CONNEXION_STRING
          value: "Data Source=erabliere-db-service;Initial Catalog=ErabliereAPI;User ID=SA;Password=#{DATABASE_PASSWORD}"
        - name: SQL_USE_STARTUP_MIGRATION
          value: "true"
        - name: DEBUG_HEADERS
          value: "true"