apiVersion: v1
kind: Service
metadata:
  name: erabliere-api-service
  labels:
    run: erabliereapi
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: erabliereapi