apiVersion: v1
kind: Service
metadata:
  name: loginpage-service
  labels:
    run: loginpage
  namespace: erabliere-api
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: loginpage