apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginpage-deployment
  labels:
    app: loginpage
  namespace: erabliere-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginpage
  template:
    metadata:
      labels:
        app: loginpage
    spec:
      containers:
      - name: loginpage
        image: oryd/hydra-login-consent-node:v1.9.2
        ports:
        - containerPort: 3000