apiVersion: v1
kind: Service
metadata:
  name: serveur-identite-service
  labels:
    run: serveuridentite
  namespace: erabliere-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: serveuridentite