apiVersion: apps/v1
kind: Deployment
metadata:
  name: serveur-identite-deployment
  labels:
    app: serveuridentite
  namespace: erabliere-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serveuridentite
  template:
    metadata:
      labels:
        app: serveuridentite
    spec:
      volumes:
      - name: identity-server-clients-files
        configMap:
          name: identity-server-clients
      containers:
      - name: serveuridentite
        image: #{REGISTRY_HOSTNAME}/#{IMAGE_NAME}:#{IMAGE_TAG}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: identity-server-clients-files
          mountPath: /app/secrets
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: USE_FORWARDED_HEADERS
          value: "true"
        - name: IDENTITY_SERVER_ORIGIN
          value: "https://oauth2.freddycoder.com"
        - name: SECRETS_FOLDER
          value: "/app/secrets"