name: ErabliereAPI-Test

on: 
  workflow_run:
      workflows: ["ErabliereAPI-Image"]
      branches: [master]
      types: 
        - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Connect to Azure Kubernetes
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: 'erabliereapi'
          cluster-name: 'kerabliereapi'

      # Deploy to kubernetes
      - name: Kubectl test workflow
        run: |
          kubectl config current-context
          
          # create the staging namespace
          kubectl apply -f Infrastructure/kubernetes/staging/namespace.yaml

          # create the staging deployment
          kubectl apply -f Infrastructure/kubernetes/staging/deployment.yaml -n erabliereapi-staging

          # wait for the deployment to be ready
          kubectl rollout status deployment erabliereapi-deployment -n erabliereapi-staging

          # create the staging service
          kubectl apply -f Infrastructure/kubernetes/staging/service.yaml -n erabliereapi-staging

          # create a configmap from the Postman folder
          kubectl create configmap erabliereapi-postman-test --from-file=Postman/ --dry-run=client -o yaml | kubectl apply -f - -n erabliereapi-staging

          # create the newman pod
          kubectl apply -f Infrastructure/kubernetes/staging/newman-pod.yaml -n erabliereapi-staging

          # wait for the newman pod to be ready
          kubectl wait --for=condition=Ready -n erabliereapi-staging pod/securetesting-newman --timeout=60s

          # attach to the newman pod
          kubectl attach securetesting-newman -c securetesting-newman -n erabliereapi-staging

          # extract the test results
          kubectl cp securetesting-newman:test-results . -c file-copy -n erabliereapi-staging

          # delete the staging namespace
          kubectl delete namespace erabliereapi-staging

      # Analyse newman results
      - name: Analyse newman result
        run: |
          # analyse the newman results
          cat junit-report.xml