name: ErabliereAPI-Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - PythonScripts/**
      - .github/**
      - Infrastructure/**
      - Postman/**
      - .gitignore
      - '*.png'
      - IdentityServer/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - PythonScripts/**
      - .github/**
      - Infrastructure/**
      - Postman/**
      - .gitignore
      - '*.png'
      - IdentityServer/**
  workflow_dispatch:

env:
  REGISTRY_HOSTNAME: erabliereapi
  IMAGE_NAME: erabliereapi
  IMAGE_TAG: v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.registryUsername }}
          password: ${{ secrets.registryPassword }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: github.ref == 'refs/heads/master'
          tags: $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG
