# this is a github action that reboot an azure webapp
# and then run the test script locally targeting the webapp
name: ErabliereAPI-Test-Demo

on: 
  workflow_run:
      workflows: ["ErabliereAPI-Image"]
      branches: [master]
      types: 
        - completed
  workflow_dispatch:

env:
  EXAMPLE: exemple

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
        with: # Set Azure credentials secret as an input
          creds: ${{ secrets.AZURE_DEMO_CREDENTIALS }}
          enable-AzPSSession: true

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Reboot the webapp
        run: |
          az webapp restart --name erabliereapi-demo --resource-group erabliereapi-demo
          for i in {1..9}; do
            echo "Waiting for webapp to restart... $((i*10))s elapsed"
            sleep 10
          done

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: matt-ball/newman-action@170d252f10d199d75d6be4c739b48a3bd5f15ece
        with:
          collection: Postman/ErablièreAPI.postman_collection.json
          environment: Postman/ErabliereAPI-Demo.postman_environment.json
          reporters: '["cli","junit"]'

      - name: Install node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
            node-version: '26'

      - name: Install dependencies & run post install script
        run: |
          cd ErabliereIU
          echo "min-release-age=1" > .npmrc
          echo "registry=https://registry.npmjs.org" >> .npmrc
          echo "loglevel=info" >> .npmrc
          npm ci
          

      - name: Cypress run
        uses: cypress-io/github-action@dace029018fcdf86e0df89a31bc3cfa5b32570d8
        with:
          record: true
          working-directory: ErabliereIU
          config: video=false,baseUrl=https://erabliereapi-demo.azurewebsites.net
        env:
          # pass the Cypress Cloud project ID as an environment variable or store it in the Cypress configuration file
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORDING_KEY }}
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload screenshots
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: failure()
        with:
          name: screenshots
          path: /home/runner/work/ErabliereApi/ErabliereApi/ErabliereIU/cypress/screenshots

  promote_docker_image:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # Login into dockerhub
      # skip this test if the run is trigger form a pull request from a fork
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          username: ${{ secrets.registryUsername }}
          password: ${{ secrets.registryPassword }}

      - name: Pull the image
        if: github.event_name != 'pull_request'
        run: |
          docker pull erabliereapi/erabliereapi:v3-dev

      - name: Tag the v3-dev as v3 and latest
        if: github.event_name != 'pull_request'
        run: |
          docker tag erabliereapi/erabliereapi:v3-dev erabliereapi/erabliereapi:v3
          docker tag erabliereapi/erabliereapi:v3-dev erabliereapi/erabliereapi:latest

      - name: Push the image
        if: github.event_name != 'pull_request'
        run: |
          docker push erabliereapi/erabliereapi:v3
          docker push erabliereapi/erabliereapi:latest