name: ErabliereAPI-Test

on: 
  workflow_run:
      workflows: ["ErabliereAPI-Test"]
      branches: [master]
      types: 
        - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Connect to Azure Kubernetes
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: 'erabliereapi'
          cluster-name: 'kerabliereapi'

      # Deploy to kubernetes
      - name: Kubectl restart deployment
        run: |
          kubectl config current-context
          kubectl rollout restart deployment erabliereapi-deployment -n erabliereapi-prod