name: ErabliereAPI-Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - PythonScripts/**
      - .github/**
      - Infrastructure/**
      - Postman/**
      - .gitignore
      - '*.png'
      - IdentityServer/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - PythonScripts/**
      - .github/**
      - Infrastructure/**
      - Postman/**
      - .gitignore
      - '*.png'
      - IdentityServer/**
  workflow_dispatch:

env:
  REGISTRY_HOSTNAME: erabliereapi
  IMAGE_NAME: erabliereapi
  IMAGE_TAG: v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.registryUsername }}
          password: ${{ secrets.registryPassword }}

      - name: Docker build
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
        
      # Tag the images
      - name: Docker tag
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker tag $IMAGE_NAME:$IMAGE_TAG $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG

      # Push the image
      - name: Docker push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker push $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG
