# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic Publish'

on:
  push:
    branches:
      - master
    paths:
      - ErabliereIU/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ErabliereIU/**
  workflow_dispatch:

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Install dependencies
        run: |
          cd ErabliereIU
          npm install
          echo ${{ github.event_name }}
          echo ${{ github.repository }}

      # If the CHROMATIC_PROJECT_TOKEN secret is empty, use npm run chromatic
      - name: Build the storybook
        if: ${{ secrets.CHROMATIC_PROJECT_TOKEN }} == ''
        run: |
          cd ErabliereIU
          npm run chromatic

      #👇 Adds Chromatic as a step in the workflow
      # If the CHROMATIC_PROJECT_TOKEN secret is set, use chamaui latest action
      - uses: chromaui/action@latest
        if: ${{ secrets.CHROMATIC_PROJECT_TOKEN }} != ''
        # Options required for Chromatic's GitHub Action
        with:
          workingDir: ./ErabliereIU
          #👇 Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}