# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic Publish'

on:
  push:
    branches:
      - master
    paths-ignore:
      - PythonScripts/**
      - .github/**
      - Infrastructure/**
      - Postman/**
      - .gitignore
      - '*.png'
      - IdentityServer/**
      - '*.ps1'
      - '*.yaml'
      - '*.md'
      - Diagrams/**
      - ErabliereAPI.Proxy/**
      - ErabliereApi/**
      - ErabliereApi*/**
      - ErabliereModel/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - PythonScripts/**
      - .github/**
      - Infrastructure/**
      - Postman/**
      - .gitignore
      - '*.png'
      - IdentityServer/**
      - '*.ps1'
      - '*.yaml'
      - '*.md'
      - Diagrams/**
      - ErabliereAPI.Proxy/**
      - ErabliereApi/**
      - ErabliereApi*/**
      - ErabliereModel/**
  workflow_dispatch:

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm
      #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        workingDir: './EraliereIU'
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
