name: ExtraireInfoHmi-Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
    - 'Infrastructure/docker/extraireInfoHmi.dockerfile'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'Infrastructure/docker/extraireInfoHmi.dockerfile'

env:
  REGISTRY_HOSTNAME: erabliereapi
  IMAGE_NAME: extraireinfohmi
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login into dockerhub
      - name: Login into dockerhub
        run: echo ${{ secrets.registryPassword }} | docker login -u ${{ secrets.registryUsername }} --password-stdin

      # Build the image
      - name: Docker build
        run: docker build -f Infrastructure/docker/extraireInfoHmi.dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
        
      # Tag the images
      - name: Docker tag
        run: docker tag $IMAGE_NAME:$IMAGE_TAG $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG

      # Push the image
      - name: Docker push
        if: github.ref == 'refs/heads/master'
        run: docker push $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG
