name: ErabliereAPI.Proxy-Publish

on:
  push:
    branches:
      - master
    paths:
      - ErabliereAPI.Proxy/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ErabliereAPI.Proxy/**
  workflow_dispatch:

env:
  name: PROJECT_PATH
  value: ErabliereAPI.Proxy/ErabliereAPI.Proxy.csproj

# This a a github action generating a nuget package and pushing it to the nuget.org
# The projet is call ErabliereAPI.Proxy and the process to build the package is
# 1. Do a dotnet build
# 2. Push the package found in the bin/Release folder to the nuget.org

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: '9.0.x'

      - name: dotnet build
        run: dotnet build $PROJECT_PATH -c Release -o bin/Release

      - name: Push the package to nuget.org
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          # Extract the version from the csproj file
          VERSION=$(grep -Eoi "<version>([[:digit:]\.]+)</version>" ErabliereAPI.Proxy/ErabliereAPI.Proxy.csproj | sed -n 's:.*<Version>\(.*\)</Version>.*:\1:p')

          # Publish the package to nuget.org
          dotnet nuget push ./bin/Release/ErabliereAPI.Proxy.$VERSION.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.ERABLIEREAPIPROXYNUGETAPIKEY }}
